// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:4000' | (string & {});
};

export type HealthResponse = {
    status: string;
    time: string;
};

export type Tenant = {
    id: string;
    name: string;
    slug: string;
    environment: string;
};

export type User = {
    id: string;
    email: string;
    role: string;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type RegisterRequest = {
    businessName: string;
    email: string;
    password: string;
};

export type AuthResponse = {
    token: string;
    tenant: Tenant;
    user: User;
};

export type MeResponse = {
    id: string;
    email: string;
    role: string;
    createdAt: string;
    tenant: {
        id: string;
        name: string;
        slug: string;
        environment: string;
        status: string;
    };
};

export type TenantProfile = {
    id: string;
    name: string;
    slug: string;
    status: string;
    environment: string;
    settlementCurrency: string;
    taxRateBps: number;
    taxExempt: boolean;
    createdAt: string;
    notifyWebhookUrl: string | null;
    notifyEmail: string | null;
};

export type TenantUpdateResponse = {
    id: string;
    name: string;
    slug: string;
    settlementCurrency: string;
    taxRateBps: number;
    taxExempt: boolean;
    notifyWebhookUrl: string | null;
    notifyEmail: string | null;
};

export type UserListItem = {
    id: string;
    email: string;
    role: string;
    createdAt: string;
};

export type ProviderConfigListItem = {
    id: string;
    provider: string;
    status: string;
    environment: string;
    createdAt: string;
    updatedAt: string;
    credentials: {
        [key: string]: unknown;
    };
};

export type ProviderConfigUpsertResponse = {
    id: string;
    provider: string;
    status: string;
    warnings: Array<string>;
};

export type ProviderTestResponse = {
    connected: boolean;
    status: string;
    error: string | null;
};

export type PaymentLinkCreateResponse = {
    id: string;
    slug: string;
    url: string;
    amount: number | string;
    currency: string;
    description: string;
    reference: string;
    status: string;
    isRecurring: boolean;
    billingInterval: string | null;
    intervalValue: number | null;
    createdAt: string;
};

export type PaymentLinkListItem = {
    id: string;
    slug: string;
    url: string;
    amount: number | string;
    currency: string;
    description: string;
    reference: string;
    provider: string;
    status: string;
    attemptCount: number;
    maxAttempts: number;
    expiresAt: string | null;
    isRecurring: boolean;
    billingInterval: string | null;
    intervalValue: number | null;
    createdAt: string;
};

export type PaymentLinkDetail = {
    id: string;
    tenantId: string;
    slug: string;
    amount: number | string;
    currency: string;
    description: string;
    reference: string;
    customerName: string | null;
    customerEmail: string | null;
    customerPhone: string | null;
    provider: string;
    status: string;
    maxAttempts: number;
    attemptCount: number;
    expiresAt: string | null;
    isRecurring: boolean;
    billingInterval: string | null;
    intervalValue: number | null;
    maxRetries: number;
    isInstallment: boolean;
    createdAt: string;
    updatedAt: string;
    url: string;
    _count: {
        paymentIntents: number;
    };
};

export type PublicCheckoutResponse = {
    slug: string;
    merchantName: string;
    amount: number | string;
    currency: string;
    description: string;
    customerName: string | null;
    customerEmail: string | null;
    customerPhone: string | null;
    provider: string;
    isRecurring: boolean;
    isInstallment: boolean;
    billingInterval: string | null;
    intervalValue: number | null;
};

export type WebhookAck = {
    received: boolean;
    duplicate?: boolean;
};

export type CreateIntentRequest = {
    provider: 'NAPS' | 'VPS' | 'STRIPE' | 'PAYPAL' | 'ADYEN';
    amount: number;
    currency?: string;
    reference: string;
    description: string;
    returnUrl: string;
    successUrl?: string;
    cancelUrl?: string;
    failureUrl?: string;
    webhookUrl?: string;
    customerEmail?: string;
    customerName?: string;
    customerPhone?: string;
    customerCountry?: string;
    customerLocale?: string;
    isPreauth?: boolean;
    metadata?: {
        [key: string]: unknown;
    };
    walletMode?: 'apple_pay' | 'google_pay';
    checkoutMode?: 'hosted' | 'element';
};

export type CreateIntentResponse = {
    intentId: string;
    correlationId: string;
    checkoutUrl: string;
    redirectUrl: string | null;
    providerData: {
        [key: string]: unknown;
    } | null;
    stripeData: {
        clientSecret: string;
        publishableKey: string;
    } | null;
    idempotent?: boolean;
    riskVerdict: string | null;
};

export type IntentStatusResponse = {
    status: string;
    providerRef: string | null;
};

export type IntentActionResult = {
    intentId: string;
    status: string;
};

export type PayRequest = {
    customerIp?: string;
    customerEmail?: string | '';
    customerName?: string;
    installmentPlanId?: string;
    downPaymentAmount?: number;
};

export type PayResponse = {
    intentId: string;
    agreementId?: string;
    redirectUrl: string;
    providerData: {
        [key: string]: unknown;
    } | null;
};

export type PublicRelayResponse = {
    status: string;
    providerData: {
        paywallUrl?: string;
        payload?: string;
        signature?: string;
        mode?: string;
        chargeId?: string;
        redirectUrl?: string;
    } | null;
};

export type Transaction = {
    id: string;
    correlationId: string;
    status: string;
    provider: string;
    providerRef: string | null;
    providerTransactionId: string | null;
    amount: number | string | unknown;
    currency: string | null;
    paymentLink: {
        title: string | null;
        slug: string;
    } | null;
    reference: string | null;
    description: string | null;
    hasRefund: boolean;
    refundStatus: string | null;
    riskVerdict: string | null;
    createdAt: string;
    updatedAt: string;
};

export type TransactionDetail = {
    id: string;
    tenantId: string;
    paymentLinkId: string | null;
    status: string;
    provider: string;
    providerRef: string | null;
    correlationId: string;
    providerData: {
        [key: string]: unknown;
    } | null;
    customerIp: string | null;
    metadata: {
        [key: string]: unknown;
    } | null;
    riskVerdict: string | null;
    createdAt: string;
    updatedAt: string;
    paymentLink: {
        id: string;
        slug: string;
        amount: number | string;
        currency: string;
        description: string;
        reference: string;
        customerName: string | null;
        customerEmail: string | null;
        customerPhone: string | null;
        provider: string;
        status: string;
        createdAt: string;
    } | null;
    providerTxs: Array<{
        id: string;
        provider: string;
        providerTransactionId: string | null;
        rawResponse: {
            [key: string]: unknown;
        };
        createdAt: string;
    }>;
    refunds: Array<{
        id: string;
        status: string;
        amount: number | string;
        currency: string;
        providerRefundRef: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
    webhookEvents: Array<{
        id: string;
        provider: string;
        signatureVerified: boolean;
        processed: boolean;
        mappedStatus: string | null;
        processingError: string | null;
        createdAt: string;
    }>;
    amount: number | string | unknown;
    currency: string | null;
    timeline: Array<{
        type: string;
        timestamp: string;
        detail: string;
    }>;
};

export type PaymentIntentDetail = {
    id: string;
    tenantId: string;
    paymentLinkId: string | null;
    status: string;
    provider: string;
    providerRef: string | null;
    correlationId: string;
    providerData: {
        [key: string]: unknown;
    } | null;
    customerIp: string | null;
    metadata: {
        [key: string]: unknown;
    } | null;
    riskVerdict: string | null;
    createdAt: string;
    updatedAt: string;
    paymentLink: {
        slug: string;
        amount: number | string;
        currency: string;
        description: string;
        reference: string;
        customerName: string | null;
        customerEmail: string | null;
        customerPhone: string | null;
    } | null;
    providerTxs: Array<{
        id: string;
        provider: string;
        providerTransactionId: string | null;
        rawResponse: {
            [key: string]: unknown;
        };
        createdAt: string;
    }>;
    refunds: Array<{
        id: string;
        status: string;
        amount: number | string;
        createdAt: string;
    }>;
    webhookEvents: Array<{
        id: string;
        signatureVerified: boolean;
        processed: boolean;
        mappedStatus: string | null;
        createdAt: string;
    }>;
};

export type RefundResponse = {
    id: string;
    status: string;
    amount: number | string;
    currency: string;
    providerRefundRef: string | null;
};

export type DashboardSummary = {
    today: {
        count: number;
        total: number;
        currency: string;
    };
    thisWeek: {
        count: number;
        total: number;
        currency: string;
    };
    payoutStatus: string;
};

export type ApiKeyListItem = {
    id: string;
    name: string;
    keyPrefix: string;
    lastUsedAt: string | null;
    createdAt: string;
};

export type ApiKeyCreateResponse = {
    id: string;
    name: string;
    keyPrefix: string;
    rawKey: string;
    createdAt: string;
};

export type BillingEvent = {
    id: string;
    chargeId: string;
    status: string;
    amount: number | string;
    currency: string;
    attemptNumber: number;
    billingPeriodStart: string | null;
    billingPeriodEnd: string | null;
    processedAt: string | null;
    errorMessage: string | null;
    vpsTransactionId: string | null;
};

export type SubscriptionListItem = {
    id: string;
    customerId: string;
    status: string;
    amount: number | string;
    currency: string;
    intervalType: string;
    intervalValue: number;
    nextBillingDate: string | null;
    retryCount: number;
    billingEventCount: number;
    createdAt: string;
};

export type SubscriptionDetail = {
    id: string;
    tenantId: string;
    customerId: string;
    initialPaymentIntentId: string;
    paymentLinkId: string | null;
    inngestRunId: string | null;
    status: string;
    amount: number | string;
    currency: string;
    intervalType: string;
    intervalValue: number;
    nextBillingDate: string | null;
    currentPeriodStart: string | null;
    currentPeriodEnd: string | null;
    trialEndDate: string | null;
    retryCount: number;
    maxRetries: number;
    createdAt: string;
    updatedAt: string;
    billingEvents: Array<BillingEvent>;
};

export type InstallmentPlanListItem = {
    id: string;
    name: string;
    durationMonths: number;
    annualInterestRate: number;
    minAmount: number | null;
    maxAmount: number | null;
    isActive: boolean;
    agreementCount: number;
    createdAt: string;
};

export type InstallmentPlan = {
    id: string;
    tenantId: string;
    name: string;
    durationMonths: number;
    annualInterestRate: number | string;
    minAmount: number | string | unknown;
    maxAmount: number | string | unknown;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
};

export type InstallmentPlanSummary = {
    name: string;
    durationMonths: number;
    annualInterestRate: number | string;
};

export type InstallmentCharge = {
    id: string;
    installmentNumber: number;
    amount: number | string;
    currency: string;
    status: string;
    attemptNumber: number;
    processedAt: string | null;
    errorMessage: string | null;
};

export type InstallmentAgreementListItem = {
    id: string;
    customerId: string;
    plan: InstallmentPlanSummary;
    status: string;
    principalAmount: number;
    downPayment: number;
    installmentAmount: number;
    totalInstallments: number;
    paidCount: number;
    currency: string;
    nextChargeDate: string | null;
    chargeCount: number;
    createdAt: string;
};

export type InstallmentAgreementDetail = {
    id: string;
    tenantId: string;
    customerId: string;
    planId: string;
    paymentLinkId: string | null;
    initialPaymentIntentId: string;
    status: string;
    principalAmount: number;
    downPayment: number;
    installmentAmount: number;
    totalInstallments: number;
    paidCount: number;
    currency: string;
    nextChargeDate: string | null;
    createdAt: string;
    updatedAt: string;
    plan: InstallmentPlanSummary;
    installmentCharges: Array<InstallmentCharge>;
};

export type AdminTenantListItem = {
    id: string;
    name: string;
    slug: string;
    status: string;
    environment: string;
    createdAt: string;
    transactionCount: number;
    providerConfigs: Array<{
        provider: string;
        status: string;
    }>;
    lastTransactionAt: string | null;
};

export type AdminTenantDetail = {
    id: string;
    name: string;
    slug: string;
    status: string;
    environment: string;
    notifyEmail: string | null;
    notifyWebhookUrl: string | null;
    createdAt: string;
    updatedAt: string;
    users: Array<{
        id: string;
        email: string;
        role: string;
        createdAt: string;
    }>;
    providerConfigs: Array<{
        id: string;
        provider: string;
        status: string;
        environment: string;
        updatedAt: string;
    }>;
};

export type AdminWebhookEvent = {
    id: string;
    provider: string;
    tenantId: string | null;
    paymentIntentId: string | null;
    signatureVerified: boolean;
    processed: boolean;
    processingError: string | null;
    mappedStatus: string | null;
    idempotencyKey: string | null;
    createdAt: string;
    rawPayload: {
        [key: string]: unknown;
    };
};

export type ProviderHealthRecord = {
    id: string;
    provider: string;
    status: string;
    notes: string | null;
    updatedAt: string | null;
};

export type AdminVpsTenant = {
    id: string;
    name: string;
};

export type LedgerEntry = {
    id: string;
    postingId: string;
    account: string;
    direction: string;
    category: string;
    amount: number | string;
    balanceAfter: number | string;
    sourceType: string | null;
    sourceId: string | null;
    createdAt: string;
};

export type LedgerResponse = {
    balanced: boolean;
    balances: {
        [key: string]: number | string;
    };
    entries: Array<LedgerEntry>;
};

export type FeeSchedule = {
    id: string;
    version: number;
    name: string | null;
    feeType: string;
    flatCents: number | null;
    percentageBps: number | null;
    perMethodCents: {
        [key: string]: number;
    } | null;
    tiersCents: Array<{
        upToCents: number;
        percentageBps: number;
    }> | null;
    currency: string;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
};

export type SettlementPolicy = {
    id: string;
    version: number;
    name: string | null;
    industry: string | null;
    mcc: string | null;
    availabilityMode: string;
    availabilityDelayDays: number | null;
    reserveType: string;
    reservePercentageBps: number | null;
    reserveHoldDays: number | null;
    reserveFixedCents: number | null;
    payoutSchedule: string;
    payoutMinCents: number | null;
    reversalFunding: string;
    allowNegative: boolean;
    splittingEnabled: boolean;
    payoutRail: string;
    feeScheduleId: string | null;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
};

export type SettlementSummary = {
    currency: string;
    availableCents: number;
    scheduledCents: number;
    eligibleCents: number;
    feesCents: number;
    reserveCents: number;
    paidOutCents: number;
    payoutRail: string | null;
};

export type FinanceConfigResponse = {
    capabilities: Array<string>;
    preset: string | null;
    walletCommissionBasis: string;
};

export type PayoutItem = {
    id: string;
    ledgerEntryId: string;
    amountCents: number;
};

export type Payout = {
    id: string;
    status: string;
    provider: string;
    method: string;
    currency: string;
    amountCents: number;
    feeCents: number;
    providerTransferId: string | null;
    idempotencyKey: string;
    items: Array<PayoutItem>;
    createdAt: string;
    updatedAt: string;
};

export type Recovery = {
    id: string;
    status: string;
    amountCents: number;
    currency: string;
    createdAt: string;
};

export type Dispute = {
    id: string;
    status: string;
    provider: string;
    providerDisputeId: string;
    paymentIntentId: string | null;
    amountCents: number;
    feeCents: number;
    currency: string;
    reason: string | null;
    evidenceDueDate: string | null;
    recovery: Recovery & unknown;
    createdAt: string;
    updatedAt: string;
};

export type SplitParty = {
    id: string;
    slug: string;
    name: string;
    type: string;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
};

export type SplitRule = {
    id: string;
    name: string;
    trigger: string;
    shares: {
        [key: string]: unknown;
    };
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
};

export type Split = {
    id: string;
    splitRuleId: string | null;
    sourceType: string;
    sourceId: string;
    partyId: string;
    amountCents: number;
    currency: string;
    status: string;
    heldUntil: string | null;
    createdAt: string;
    updatedAt: string;
};

export type ReconciliationLine = {
    id: string;
    reference: string;
    amountCents: number;
    currency: string;
    status: string;
    matchedAmountCents: number | null;
    differenceAmountCents: number | null;
    createdAt: string;
};

export type ReconciliationSummary = {
    exactCount: number;
    amountDiffCount: number;
    missingInternal: Array<{
        reference: string;
        amountCents: number;
    }>;
    missingExternal: Array<{
        reference: string;
        amountCents: number;
    }>;
    externalTotalCents: number;
    internalTotalCents: number;
    netDifferenceCents: number;
};

export type ReconciliationReport = {
    id: string;
    provider: string;
    currency: string;
    periodStart: string | null;
    periodEnd: string | null;
    status: string;
    summary: ReconciliationSummary & unknown;
    lines: Array<ReconciliationLine>;
    createdAt: string;
    updatedAt: string;
};

export type SettlementStatementItem = {
    id: string;
    category: string;
    amountCents: number;
    entryCount: number;
};

export type SettlementStatement = {
    id: string;
    periodStart: string;
    periodEnd: string;
    currency: string;
    status: string;
    openingBalanceCents: number;
    closingBalanceCents: number;
    netCents: number;
    finalizedAt: string | null;
    items: Array<SettlementStatementItem>;
    createdAt: string;
    updatedAt: string;
};

export type MerchantOnboarding = {
    id: string;
    tenantId: string;
    status: string;
    legalName: string | null;
    entityType: string | null;
    registrationNumber: string | null;
    country: string | null;
    businessAddress: string | null;
    website: string | null;
    contactEmail: string | null;
    industry: string | null;
    mcc: string | null;
    riskTier: string;
    submittedAt: string | null;
    reviewerId: string | null;
    reviewNotes: string | null;
    rejectionReason: string | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
};

export type OnboardingPolicySpec = {
    industry: string | null;
    mcc: string | null;
    availabilityMode: string;
    availabilityDelayDays: number | null;
    reserveType: string;
    reservePercentageBps: number | null;
    reserveHoldDays: number | null;
    reserveFixedCents: number | null;
    payoutSchedule: string;
    payoutMinCents: number | null;
    reversalFunding: string;
    allowNegative: boolean;
    splittingEnabled: boolean;
};

export type WalletTransaction = {
    id: string;
    type: string;
    amountCents: number;
    currency: string;
    balanceAfterCents: number;
    sourceType: string | null;
    sourceId: string | null;
    createdAt: string;
};

export type Wallet = {
    id: string;
    tenantId: string;
    ownerType: string;
    ownerId: string;
    balanceCents: number;
    currency: string;
    status: string;
    createdAt: string;
    updatedAt: string;
};

export type WalletOpResponse = Wallet & {
    transaction: WalletTransaction;
};

export type WalletDetail = Wallet & {
    transactions: Array<WalletTransaction>;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * OK
     */
    200: HealthResponse;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type PublicCheckoutData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/public/checkout/{slug}';
};

export type PublicCheckoutErrors = {
    /**
     * Payment link not found
     */
    404: unknown;
    /**
     * Link canceled / paid / expired
     */
    410: unknown;
};

export type PublicCheckoutResponses = {
    /**
     * OK
     */
    200: PublicCheckoutResponse;
};

export type PublicCheckoutResponse2 = PublicCheckoutResponses[keyof PublicCheckoutResponses];

export type PublicPayData = {
    body?: PayRequest;
    path: {
        slug: string;
    };
    query?: never;
    url: '/public/checkout/{slug}/pay';
};

export type PublicPayErrors = {
    /**
     * Plan required / amount constraints
     */
    400: unknown;
    /**
     * Payment link not found
     */
    404: unknown;
    /**
     * Link inactive / expired
     */
    410: unknown;
    /**
     * Maximum payment attempts reached
     */
    429: unknown;
};

export type PublicPayResponses = {
    /**
     * OK
     */
    200: PayResponse;
};

export type PublicPayResponse = PublicPayResponses[keyof PublicPayResponses];

export type PublicInstallmentPlansData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/public/installment-plans/{slug}';
};

export type PublicInstallmentPlansErrors = {
    /**
     * Not an installment link
     */
    400: unknown;
    /**
     * Payment link not found
     */
    404: unknown;
};

export type PublicInstallmentPlansResponses = {
    /**
     * OK
     */
    200: {
        currency: string;
        principal: number | string;
        plans: Array<{
            planId: string;
            name: string;
            durationMonths: number;
            annualInterestRate: number;
            installmentAmount: number;
            totalAmount: number;
            totalInterest: number;
            minAmount: number | null;
            maxAmount: number | null;
        }>;
    };
};

export type PublicInstallmentPlansResponse = PublicInstallmentPlansResponses[keyof PublicInstallmentPlansResponses];

export type PublicRelayData = {
    body?: never;
    path: {
        correlationId: string;
    };
    query?: never;
    url: '/public/pay/{correlationId}';
};

export type PublicRelayErrors = {
    /**
     * Payment session not found
     */
    404: unknown;
};

export type PublicRelayResponses = {
    /**
     * OK (JSON for API clients; HTML for browsers)
     */
    200: PublicRelayResponse;
};

export type PublicRelayResponse2 = PublicRelayResponses[keyof PublicRelayResponses];

export type NapsWebhookData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/webhooks/naps';
};

export type NapsWebhookErrors = {
    /**
     * Invalid JSON payload
     */
    400: unknown;
    /**
     * Invalid webhook signature
     */
    401: unknown;
};

export type NapsWebhookResponses = {
    /**
     * Received (and possibly deduplicated)
     */
    200: WebhookAck;
};

export type NapsWebhookResponse = NapsWebhookResponses[keyof NapsWebhookResponses];

export type VpsWebhookData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/webhooks/vps';
};

export type VpsWebhookErrors = {
    /**
     * Invalid JSON payload
     */
    400: unknown;
    /**
     * Invalid webhook signature
     */
    401: unknown;
};

export type VpsWebhookResponses = {
    /**
     * Received (and possibly deduplicated)
     */
    200: WebhookAck;
};

export type VpsWebhookResponse = VpsWebhookResponses[keyof VpsWebhookResponses];

export type StripeWebhookData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/webhooks/stripe';
};

export type StripeWebhookErrors = {
    /**
     * Invalid JSON payload
     */
    400: unknown;
    /**
     * Invalid webhook signature
     */
    401: unknown;
};

export type StripeWebhookResponses = {
    /**
     * Received (and possibly deduplicated)
     */
    200: WebhookAck;
};

export type StripeWebhookResponse = StripeWebhookResponses[keyof StripeWebhookResponses];

export type LoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Invalid credentials
     */
    401: unknown;
};

export type LoginResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RegisterData = {
    body?: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * Email already taken
     */
    409: unknown;
};

export type RegisterResponses = {
    /**
     * Created
     */
    201: AuthResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetMeErrors = {
    /**
     * Unauthenticated
     */
    401: unknown;
};

export type GetMeResponses = {
    /**
     * OK
     */
    200: MeResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ForgotPasswordData = {
    body?: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type ForgotPasswordResponses = {
    /**
     * OK
     */
    200: {
        message: string;
    };
};

export type ForgotPasswordResponse = ForgotPasswordResponses[keyof ForgotPasswordResponses];

export type ResetPasswordData = {
    body?: {
        token: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type ResetPasswordResponses = {
    /**
     * OK
     */
    200: {
        message: string;
    };
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type GetTenantData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenant';
};

export type GetTenantResponses = {
    /**
     * OK
     */
    200: TenantProfile;
};

export type GetTenantResponse = GetTenantResponses[keyof GetTenantResponses];

export type UpdateTenantData = {
    body?: {
        name?: string;
        notifyWebhookUrl?: string | null;
        notifyEmail?: string | null;
        rotateWebhookSigningSecret?: boolean;
        settlementCurrency?: 'MAD' | 'USD' | 'EUR' | 'GBP' | 'CAD';
        taxRateBps?: number;
        taxExempt?: boolean;
    };
    path?: never;
    query?: never;
    url: '/tenant';
};

export type UpdateTenantResponses = {
    /**
     * OK
     */
    200: TenantUpdateResponse;
};

export type UpdateTenantResponse = UpdateTenantResponses[keyof UpdateTenantResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type ListUsersResponses = {
    /**
     * OK
     */
    200: Array<UserListItem>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type InviteUserData = {
    body?: {
        email: string;
        role: 'STAFF' | 'OWNER';
        password: string;
    };
    path?: never;
    query?: never;
    url: '/users/invite';
};

export type InviteUserErrors = {
    /**
     * Email already taken
     */
    409: unknown;
};

export type InviteUserResponses = {
    /**
     * Created
     */
    201: User;
};

export type InviteUserResponse = InviteUserResponses[keyof InviteUserResponses];

export type ChangeUserRoleData = {
    body?: {
        role: 'STAFF' | 'OWNER';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}/role';
};

export type ChangeUserRoleErrors = {
    /**
     * Cannot remove the only owner
     */
    400: unknown;
};

export type ChangeUserRoleResponses = {
    /**
     * OK
     */
    200: User;
};

export type ChangeUserRoleResponse = ChangeUserRoleResponses[keyof ChangeUserRoleResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type DeleteUserErrors = {
    /**
     * Cannot delete self
     */
    400: unknown;
};

export type DeleteUserResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type ListProviderConfigsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/provider-configs';
};

export type ListProviderConfigsResponses = {
    /**
     * OK
     */
    200: Array<ProviderConfigListItem>;
};

export type ListProviderConfigsResponse = ListProviderConfigsResponses[keyof ListProviderConfigsResponses];

export type UpsertProviderConfigData = {
    body?: {
        provider: 'NAPS' | 'VPS' | 'STRIPE';
        environment?: string;
        credentials?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/provider-configs';
};

export type UpsertProviderConfigErrors = {
    /**
     * Invalid credentials / unsafe test config
     */
    400: unknown;
};

export type UpsertProviderConfigResponses = {
    /**
     * OK
     */
    200: ProviderConfigUpsertResponse;
};

export type UpsertProviderConfigResponse = UpsertProviderConfigResponses[keyof UpsertProviderConfigResponses];

export type SetProviderConfigStatusData = {
    body?: {
        enabled: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/provider-configs/{id}/status';
};

export type SetProviderConfigStatusErrors = {
    /**
     * Config not found
     */
    404: unknown;
    /**
     * Config not tested / invalid
     */
    409: unknown;
};

export type SetProviderConfigStatusResponses = {
    /**
     * OK
     */
    200: {
        id: string;
        provider: string;
        status: string;
    };
};

export type SetProviderConfigStatusResponse = SetProviderConfigStatusResponses[keyof SetProviderConfigStatusResponses];

export type TestProviderConfigData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/provider-configs/{id}/test';
};

export type TestProviderConfigErrors = {
    /**
     * Config not found
     */
    404: unknown;
    /**
     * Config is disabled
     */
    409: unknown;
};

export type TestProviderConfigResponses = {
    /**
     * OK
     */
    200: ProviderTestResponse;
};

export type TestProviderConfigResponse = TestProviderConfigResponses[keyof TestProviderConfigResponses];

export type DeleteProviderConfigData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/provider-configs/{id}';
};

export type DeleteProviderConfigErrors = {
    /**
     * Config not found
     */
    404: unknown;
};

export type DeleteProviderConfigResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteProviderConfigResponse = DeleteProviderConfigResponses[keyof DeleteProviderConfigResponses];

export type ListPaymentLinksData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        limit?: string;
        offset?: string;
        status?: string;
    };
    url: '/payment-links';
};

export type ListPaymentLinksResponses = {
    /**
     * OK
     */
    200: {
        data: Array<PaymentLinkListItem>;
        total: number;
        page: number;
        limit: number;
    };
};

export type ListPaymentLinksResponse = ListPaymentLinksResponses[keyof ListPaymentLinksResponses];

export type CreatePaymentLinkData = {
    body?: {
        amount: number;
        currency?: string;
        description: string;
        reference: string;
        provider: 'NAPS' | 'VPS' | 'STRIPE';
        customerName?: string;
        customerEmail?: string | '';
        customerPhone?: string;
        expiresAt?: string;
        maxAttempts?: number;
        isRecurring?: boolean;
        billingInterval?: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'QUARTERLY' | 'ANNUAL' | 'CUSTOM';
        intervalValue?: number;
        maxRetries?: number;
        isInstallment?: boolean;
    };
    path?: never;
    query?: never;
    url: '/payment-links';
};

export type CreatePaymentLinkErrors = {
    /**
     * Provider not configured
     */
    400: unknown;
};

export type CreatePaymentLinkResponses = {
    /**
     * Created
     */
    201: PaymentLinkCreateResponse;
};

export type CreatePaymentLinkResponse = CreatePaymentLinkResponses[keyof CreatePaymentLinkResponses];

export type GetPaymentLinkData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payment-links/{id}';
};

export type GetPaymentLinkErrors = {
    /**
     * Payment link not found
     */
    404: unknown;
};

export type GetPaymentLinkResponses = {
    /**
     * OK
     */
    200: PaymentLinkDetail;
};

export type GetPaymentLinkResponse = GetPaymentLinkResponses[keyof GetPaymentLinkResponses];

export type CancelPaymentLinkData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payment-links/{id}/cancel';
};

export type CancelPaymentLinkErrors = {
    /**
     * Link not active
     */
    400: unknown;
    /**
     * Payment link not found
     */
    404: unknown;
};

export type CancelPaymentLinkResponses = {
    /**
     * OK
     */
    200: {
        id: string;
        status: string;
    };
};

export type CancelPaymentLinkResponse = CancelPaymentLinkResponses[keyof CancelPaymentLinkResponses];

export type CreatePaymentIntentData = {
    body?: CreateIntentRequest;
    path?: never;
    query?: never;
    url: '/payment-intents';
};

export type CreatePaymentIntentErrors = {
    /**
     * Provider unavailable
     */
    503: unknown;
};

export type CreatePaymentIntentResponses = {
    /**
     * Idempotent replay of a recent non-terminal intent
     */
    200: CreateIntentResponse;
    /**
     * Created
     */
    201: CreateIntentResponse;
};

export type CreatePaymentIntentResponse = CreatePaymentIntentResponses[keyof CreatePaymentIntentResponses];

export type GetPaymentIntentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payment-intents/{id}';
};

export type GetPaymentIntentErrors = {
    /**
     * Payment intent not found
     */
    404: unknown;
};

export type GetPaymentIntentResponses = {
    /**
     * OK
     */
    200: PaymentIntentDetail;
};

export type GetPaymentIntentResponse = GetPaymentIntentResponses[keyof GetPaymentIntentResponses];

export type GetPaymentIntentStatusData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payment-intents/{id}/status';
};

export type GetPaymentIntentStatusErrors = {
    /**
     * Payment intent not found
     */
    404: unknown;
};

export type GetPaymentIntentStatusResponses = {
    /**
     * OK
     */
    200: IntentStatusResponse;
};

export type GetPaymentIntentStatusResponse = GetPaymentIntentStatusResponses[keyof GetPaymentIntentStatusResponses];

export type CapturePaymentIntentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payment-intents/{id}/capture';
};

export type CapturePaymentIntentErrors = {
    /**
     * Missing provider ref / amount
     */
    400: unknown;
    /**
     * Payment intent not found
     */
    404: unknown;
    /**
     * Invalid state
     */
    409: unknown;
};

export type CapturePaymentIntentResponses = {
    /**
     * OK
     */
    200: IntentActionResult;
};

export type CapturePaymentIntentResponse = CapturePaymentIntentResponses[keyof CapturePaymentIntentResponses];

export type CancelPaymentIntentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payment-intents/{id}/cancel';
};

export type CancelPaymentIntentErrors = {
    /**
     * Missing provider ref
     */
    400: unknown;
    /**
     * Payment intent not found
     */
    404: unknown;
    /**
     * Invalid state
     */
    409: unknown;
};

export type CancelPaymentIntentResponses = {
    /**
     * OK
     */
    200: IntentActionResult;
};

export type CancelPaymentIntentResponse = CancelPaymentIntentResponses[keyof CancelPaymentIntentResponses];

export type ListTransactionsData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        limit?: string;
        offset?: string;
        status?: string;
        provider?: string;
        search?: string;
        dateFrom?: string;
        dateTo?: string;
    };
    url: '/transactions';
};

export type ListTransactionsResponses = {
    /**
     * OK
     */
    200: {
        data: Array<Transaction>;
        total: number;
        page: number;
        limit: number;
    };
};

export type ListTransactionsResponse = ListTransactionsResponses[keyof ListTransactionsResponses];

export type GetTransactionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/transactions/{id}';
};

export type GetTransactionErrors = {
    /**
     * Transaction not found
     */
    404: unknown;
};

export type GetTransactionResponses = {
    /**
     * OK
     */
    200: TransactionDetail;
};

export type GetTransactionResponse = GetTransactionResponses[keyof GetTransactionResponses];

export type RefundTransactionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/transactions/{id}/refund';
};

export type RefundTransactionErrors = {
    /**
     * Not refundable / no provider ref / missing amount
     */
    400: unknown;
    /**
     * Transaction not found
     */
    404: unknown;
    /**
     * Already refunded
     */
    409: unknown;
};

export type RefundTransactionResponses = {
    /**
     * OK
     */
    200: RefundResponse;
};

export type RefundTransactionResponse = RefundTransactionResponses[keyof RefundTransactionResponses];

export type GetDashboardSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/summary';
};

export type GetDashboardSummaryResponses = {
    /**
     * OK
     */
    200: DashboardSummary;
};

export type GetDashboardSummaryResponse = GetDashboardSummaryResponses[keyof GetDashboardSummaryResponses];

export type ExportTransactionsCsvData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
        provider?: string;
        search?: string;
        dateFrom?: string;
        dateTo?: string;
    };
    url: '/exports/transactions.csv';
};

export type ExportTransactionsCsvResponses = {
    /**
     * CSV download
     */
    200: string;
};

export type ExportTransactionsCsvResponse = ExportTransactionsCsvResponses[keyof ExportTransactionsCsvResponses];

export type ListApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api-keys';
};

export type ListApiKeysResponses = {
    /**
     * OK
     */
    200: Array<ApiKeyListItem>;
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData = {
    body?: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api-keys';
};

export type CreateApiKeyResponses = {
    /**
     * Created
     */
    201: ApiKeyCreateResponse;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type DeleteApiKeyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api-keys/{id}';
};

export type DeleteApiKeyErrors = {
    /**
     * API key not found
     */
    404: unknown;
};

export type DeleteApiKeyResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiKeyResponse = DeleteApiKeyResponses[keyof DeleteApiKeyResponses];

export type ListSubscriptionsData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        limit?: string;
        status?: string;
        customerId?: string;
    };
    url: '/subscriptions';
};

export type ListSubscriptionsResponses = {
    /**
     * OK
     */
    200: {
        data: Array<SubscriptionListItem>;
        total: number;
        page: number;
        limit: number;
    };
};

export type ListSubscriptionsResponse = ListSubscriptionsResponses[keyof ListSubscriptionsResponses];

export type CancelSubscriptionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/subscriptions/{id}';
};

export type CancelSubscriptionErrors = {
    /**
     * Already cancelled
     */
    400: unknown;
    /**
     * Subscription not found
     */
    404: unknown;
};

export type CancelSubscriptionResponses = {
    /**
     * OK
     */
    200: {
        id: string;
        status: string;
    };
};

export type CancelSubscriptionResponse = CancelSubscriptionResponses[keyof CancelSubscriptionResponses];

export type GetSubscriptionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/subscriptions/{id}';
};

export type GetSubscriptionErrors = {
    /**
     * Subscription not found
     */
    404: unknown;
};

export type GetSubscriptionResponses = {
    /**
     * OK
     */
    200: SubscriptionDetail;
};

export type GetSubscriptionResponse = GetSubscriptionResponses[keyof GetSubscriptionResponses];

export type PauseSubscriptionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/subscriptions/{id}/pause';
};

export type PauseSubscriptionErrors = {
    /**
     * Invalid state
     */
    400: unknown;
    /**
     * Subscription not found
     */
    404: unknown;
};

export type PauseSubscriptionResponses = {
    /**
     * OK
     */
    200: {
        id: string;
        status: string;
    };
};

export type PauseSubscriptionResponse = PauseSubscriptionResponses[keyof PauseSubscriptionResponses];

export type ResumeSubscriptionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/subscriptions/{id}/resume';
};

export type ResumeSubscriptionErrors = {
    /**
     * Invalid state
     */
    400: unknown;
    /**
     * Subscription not found
     */
    404: unknown;
};

export type ResumeSubscriptionResponses = {
    /**
     * OK
     */
    200: {
        id: string;
        status: string;
    };
};

export type ResumeSubscriptionResponse = ResumeSubscriptionResponses[keyof ResumeSubscriptionResponses];

export type ListSubscriptionBillingEventsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        page?: string;
        limit?: string;
    };
    url: '/subscriptions/{id}/events';
};

export type ListSubscriptionBillingEventsErrors = {
    /**
     * Subscription not found
     */
    404: unknown;
};

export type ListSubscriptionBillingEventsResponses = {
    /**
     * OK
     */
    200: {
        data: Array<BillingEvent>;
        total: number;
        page: number;
        limit: number;
    };
};

export type ListSubscriptionBillingEventsResponse = ListSubscriptionBillingEventsResponses[keyof ListSubscriptionBillingEventsResponses];

export type ListInstallmentPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/installment-plans';
};

export type ListInstallmentPlansResponses = {
    /**
     * OK
     */
    200: {
        data: Array<InstallmentPlanListItem>;
    };
};

export type ListInstallmentPlansResponse = ListInstallmentPlansResponses[keyof ListInstallmentPlansResponses];

export type CreateInstallmentPlanData = {
    body?: {
        name: string;
        durationMonths: number;
        annualInterestRate: number;
        minAmount?: number;
        maxAmount?: number;
        isActive?: boolean;
    };
    path?: never;
    query?: never;
    url: '/installment-plans';
};

export type CreateInstallmentPlanResponses = {
    /**
     * Created
     */
    201: InstallmentPlan;
};

export type CreateInstallmentPlanResponse = CreateInstallmentPlanResponses[keyof CreateInstallmentPlanResponses];

export type DeleteInstallmentPlanData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/installment-plans/{id}';
};

export type DeleteInstallmentPlanErrors = {
    /**
     * Plan not found
     */
    404: unknown;
    /**
     * Plan has active agreements
     */
    409: unknown;
};

export type DeleteInstallmentPlanResponses = {
    /**
     * OK
     */
    200: {
        deleted: boolean;
    };
};

export type DeleteInstallmentPlanResponse = DeleteInstallmentPlanResponses[keyof DeleteInstallmentPlanResponses];

export type UpdateInstallmentPlanData = {
    body?: {
        name?: string;
        durationMonths?: number;
        annualInterestRate?: number;
        minAmount?: number;
        maxAmount?: number;
        isActive?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/installment-plans/{id}';
};

export type UpdateInstallmentPlanErrors = {
    /**
     * Plan not found
     */
    404: unknown;
};

export type UpdateInstallmentPlanResponses = {
    /**
     * OK
     */
    200: InstallmentPlan;
};

export type UpdateInstallmentPlanResponse = UpdateInstallmentPlanResponses[keyof UpdateInstallmentPlanResponses];

export type ListInstallmentAgreementsData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        limit?: string;
        status?: string;
        customerId?: string;
    };
    url: '/installment-agreements';
};

export type ListInstallmentAgreementsResponses = {
    /**
     * OK
     */
    200: {
        data: Array<InstallmentAgreementListItem>;
        total: number;
        page: number;
        limit: number;
    };
};

export type ListInstallmentAgreementsResponse = ListInstallmentAgreementsResponses[keyof ListInstallmentAgreementsResponses];

export type GetInstallmentAgreementData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/installment-agreements/{id}';
};

export type GetInstallmentAgreementErrors = {
    /**
     * Agreement not found
     */
    404: unknown;
};

export type GetInstallmentAgreementResponses = {
    /**
     * OK
     */
    200: InstallmentAgreementDetail;
};

export type GetInstallmentAgreementResponse = GetInstallmentAgreementResponses[keyof GetInstallmentAgreementResponses];

export type CancelInstallmentAgreementData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/installment-agreements/{id}/cancel';
};

export type CancelInstallmentAgreementErrors = {
    /**
     * Invalid state
     */
    400: unknown;
    /**
     * Agreement not found
     */
    404: unknown;
};

export type CancelInstallmentAgreementResponses = {
    /**
     * OK
     */
    200: {
        id: string;
        status: string;
    };
};

export type CancelInstallmentAgreementResponse = CancelInstallmentAgreementResponses[keyof CancelInstallmentAgreementResponses];

export type AdminSearchPaymentsData = {
    body?: never;
    path?: never;
    query: {
        q: string;
    };
    url: '/admin/payments/search';
};

export type AdminSearchPaymentsErrors = {
    /**
     * Query too short
     */
    400: unknown;
};

export type AdminSearchPaymentsResponses = {
    /**
     * OK
     */
    200: {
        found: boolean;
        intent: {
            id: string;
            tenantId: string;
            paymentLinkId: string | null;
            status: string;
            provider: string;
            providerRef: string | null;
            correlationId: string;
            providerData: {
                [key: string]: unknown;
            } | null;
            customerIp: string | null;
            metadata: {
                [key: string]: unknown;
            } | null;
            createdAt: string;
            updatedAt: string;
            paymentLink: {
                id: string;
                slug: string;
                amount: number | string;
                currency: string;
                description: string;
                reference: string;
                customerName: string | null;
                customerEmail: string | null;
                customerPhone: string | null;
                provider: string;
                status: string;
                createdAt: string;
            } | null;
            providerTxs: Array<{
                id: string;
                provider: string;
                providerTransactionId: string | null;
                createdAt: string;
            }>;
            refunds: Array<{
                id: string;
                status: string;
                amount: number | string;
                currency: string;
                providerRefundRef: string | null;
                createdAt: string;
                updatedAt: string;
            }>;
            webhookEvents: Array<{
                id: string;
                provider: string;
                signatureVerified: boolean;
                processed: boolean;
                mappedStatus: string | null;
                processingError: string | null;
                createdAt: string;
            }>;
        } | null;
    };
};

export type AdminSearchPaymentsResponse = AdminSearchPaymentsResponses[keyof AdminSearchPaymentsResponses];

export type AdminListWebhooksData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        limit?: string;
        provider?: string;
        tenantId?: string;
        verified?: string;
        processed?: string;
        dateFrom?: string;
        dateTo?: string;
    };
    url: '/admin/webhooks';
};

export type AdminListWebhooksResponses = {
    /**
     * OK
     */
    200: {
        data: Array<AdminWebhookEvent>;
        total: number;
        page: number;
        limit: number;
    };
};

export type AdminListWebhooksResponse = AdminListWebhooksResponses[keyof AdminListWebhooksResponses];

export type AdminGetProviderHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/provider-health';
};

export type AdminGetProviderHealthResponses = {
    /**
     * OK
     */
    200: Array<ProviderHealthRecord>;
};

export type AdminGetProviderHealthResponse = AdminGetProviderHealthResponses[keyof AdminGetProviderHealthResponses];

export type AdminSetProviderHealthData = {
    body?: {
        status: 'NORMAL' | 'DEGRADED' | 'DOWN';
        notes?: string;
    };
    path: {
        provider: string;
    };
    query?: never;
    url: '/admin/provider-health/{provider}';
};

export type AdminSetProviderHealthResponses = {
    /**
     * OK
     */
    200: ProviderHealthRecord;
};

export type AdminSetProviderHealthResponse = AdminSetProviderHealthResponses[keyof AdminSetProviderHealthResponses];

export type AdminListVpsTenantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/vps-tenants';
};

export type AdminListVpsTenantsResponses = {
    /**
     * OK
     */
    200: Array<AdminVpsTenant>;
};

export type AdminListVpsTenantsResponse = AdminListVpsTenantsResponses[keyof AdminListVpsTenantsResponses];

export type AdminRecurringTestData = {
    body?: {
        tenantId?: string;
    };
    path?: never;
    query?: never;
    url: '/admin/recurring-test';
};

export type AdminRecurringTestResponses = {
    /**
     * OK
     */
    200: {
        testedAt: string;
        overallStatus: string;
        totalVpsConfigs: number;
        tenants: Array<{
            tenantId: string;
            tenantName: string;
            checks: {
                connectivity: boolean;
                profileStorage: boolean;
                hasActiveSubscriptions: boolean;
                migrationApplied: boolean;
            };
            latencyMs: number;
            vpsError?: string;
            dbError?: string;
            subscriptionStats: {
                active: number;
                pastDue: number;
                pending: number;
                cancelledLast30d: number;
                billingEventsTotal: number;
            };
            dueTodayCount: number;
        }>;
    };
};

export type AdminRecurringTestResponse = AdminRecurringTestResponses[keyof AdminRecurringTestResponses];

export type AdminListTenantsData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        limit?: string;
        status?: string;
    };
    url: '/admin/tenants';
};

export type AdminListTenantsResponses = {
    /**
     * OK
     */
    200: {
        data: Array<AdminTenantListItem>;
        total: number;
        page: number;
        limit: number;
    };
};

export type AdminListTenantsResponse = AdminListTenantsResponses[keyof AdminListTenantsResponses];

export type AdminGetTenantData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/tenants/{id}';
};

export type AdminGetTenantErrors = {
    /**
     * Tenant not found
     */
    404: unknown;
};

export type AdminGetTenantResponses = {
    /**
     * OK
     */
    200: AdminTenantDetail;
};

export type AdminGetTenantResponse = AdminGetTenantResponses[keyof AdminGetTenantResponses];

export type AdminSetTenantStatusData = {
    body?: {
        status: 'ACTIVE' | 'DISABLED';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/tenants/{id}/status';
};

export type AdminSetTenantStatusResponses = {
    /**
     * OK
     */
    200: {
        id: string;
        status: string;
    };
};

export type AdminSetTenantStatusResponse = AdminSetTenantStatusResponses[keyof AdminSetTenantStatusResponses];

export type AdminGetTenantProviderConfigsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/tenants/{id}/provider-configs';
};

export type AdminGetTenantProviderConfigsResponses = {
    /**
     * OK
     */
    200: Array<{
        id: string;
        provider: string;
        status: string;
        environment: string;
        credentials: {
            [key: string]: unknown;
        };
    }>;
};

export type AdminGetTenantProviderConfigsResponse = AdminGetTenantProviderConfigsResponses[keyof AdminGetTenantProviderConfigsResponses];

export type SimulationStartData = {
    body?: {
        tenantId: string;
        amount?: number;
        currency?: string;
        retryDelay1?: number;
        retryDelay2?: number;
        retryDelay3?: number;
    };
    path?: never;
    query?: never;
    url: '/admin/simulation/start';
};

export type SimulationStartErrors = {
    /**
     * No VPS config
     */
    400: unknown;
};

export type SimulationStartResponses = {
    /**
     * Created
     */
    201: {
        sessionId: string;
        subscriptionId: string;
        paymentIntentId: string;
        retries: {
            delay1: string;
            delay2: string;
            delay3: string;
        };
    };
};

export type SimulationStartResponse = SimulationStartResponses[keyof SimulationStartResponses];

export type SimulationStatusData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/admin/simulation/status/{sessionId}';
};

export type SimulationStatusErrors = {
    /**
     * Simulation session not found
     */
    404: unknown;
};

export type SimulationStatusResponses = {
    /**
     * OK
     */
    200: {
        sessionId: string;
        subscription: SubscriptionDetail;
        billingEvents: Array<BillingEvent>;
        done: boolean;
    };
};

export type SimulationStatusResponse = SimulationStatusResponses[keyof SimulationStatusResponses];

export type SimulationCleanupData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/admin/simulation/cleanup/{sessionId}';
};

export type SimulationCleanupResponses = {
    /**
     * OK
     */
    200: {
        deleted: {
            subscriptions: number;
            billingEvents: number;
            paymentIntents: number;
        };
    };
};

export type SimulationCleanupResponse = SimulationCleanupResponses[keyof SimulationCleanupResponses];

export type SimulationBnplPlansData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/admin/simulation/bnpl/plans/{tenantId}';
};

export type SimulationBnplPlansResponses = {
    /**
     * OK
     */
    200: {
        data: Array<{
            id: string;
            name: string;
            durationMonths: number;
            annualInterestRate: number;
            minAmount: number | null;
            maxAmount: number | null;
        }>;
    };
};

export type SimulationBnplPlansResponse = SimulationBnplPlansResponses[keyof SimulationBnplPlansResponses];

export type SimulationBnplPrepareData = {
    body?: {
        tenantId: string;
        amount?: number;
        months?: number;
        apr?: number;
    };
    path?: never;
    query?: never;
    url: '/admin/simulation/bnpl/prepare';
};

export type SimulationBnplPrepareErrors = {
    /**
     * No VPS config
     */
    400: unknown;
};

export type SimulationBnplPrepareResponses = {
    /**
     * Created
     */
    201: {
        linkId: string;
        agreementId: string;
        sessionTag: string;
        paywallUrl: string;
        paywallPayload: string;
        paywallSignature: string;
        preview: {
            totalInstallments: number;
            installmentAmount: number;
            principalAmount: number;
            apr: number;
            currency: string;
        };
    };
};

export type SimulationBnplPrepareResponse = SimulationBnplPrepareResponses[keyof SimulationBnplPrepareResponses];

export type SimulationBnplAwaitAgreementData = {
    body?: never;
    path: {
        linkId: string;
    };
    query?: never;
    url: '/admin/simulation/bnpl/await-agreement/{linkId}';
};

export type SimulationBnplAwaitAgreementResponses = {
    /**
     * OK
     */
    200: {
        found: boolean;
        agreementId?: string;
        status?: string;
        totalInstallments?: number;
        paidCount?: number;
        installmentAmount?: number;
        currency?: string;
        paymentServiceUrl?: string | null;
    };
};

export type SimulationBnplAwaitAgreementResponse = SimulationBnplAwaitAgreementResponses[keyof SimulationBnplAwaitAgreementResponses];

export type SimulationBnplFireData = {
    body?: {
        agreementId: string;
        chargeDelay?: number;
        retryDelay1?: number;
        retryDelay2?: number;
        retryDelay3?: number;
    };
    path?: never;
    query?: never;
    url: '/admin/simulation/bnpl/fire';
};

export type SimulationBnplFireErrors = {
    /**
     * Not a sim agreement / not active
     */
    400: unknown;
    /**
     * Agreement not found
     */
    404: unknown;
};

export type SimulationBnplFireResponses = {
    /**
     * OK
     */
    200: {
        agreementId: string;
        delays: {
            chargeDelay: string;
            retryDelay1: string;
            retryDelay2: string;
            retryDelay3: string;
        };
    };
};

export type SimulationBnplFireResponse = SimulationBnplFireResponses[keyof SimulationBnplFireResponses];

export type SimulationBnplStatusData = {
    body?: never;
    path: {
        agreementId: string;
    };
    query?: never;
    url: '/admin/simulation/bnpl/status/{agreementId}';
};

export type SimulationBnplStatusErrors = {
    /**
     * Agreement not found
     */
    404: unknown;
};

export type SimulationBnplStatusResponses = {
    /**
     * OK
     */
    200: {
        agreementId: string;
        agreement: InstallmentAgreementDetail;
        installmentCharges: Array<InstallmentCharge>;
        done: boolean;
    };
};

export type SimulationBnplStatusResponse = SimulationBnplStatusResponses[keyof SimulationBnplStatusResponses];

export type SimulationBnplCleanupData = {
    body?: never;
    path: {
        agreementId: string;
    };
    query?: never;
    url: '/admin/simulation/bnpl/cleanup/{agreementId}';
};

export type SimulationBnplCleanupResponses = {
    /**
     * OK
     */
    200: {
        deleted: {
            charges: number;
            agreements: number;
            paymentIntents: number;
            paymentLinks: number;
            plans: number;
        };
    };
};

export type SimulationBnplCleanupResponse = SimulationBnplCleanupResponses[keyof SimulationBnplCleanupResponses];

export type SimulationDirectPrepareData = {
    body?: {
        tenantId: string;
        amount?: number;
    };
    path?: never;
    query?: never;
    url: '/admin/simulation/direct/prepare';
};

export type SimulationDirectPrepareErrors = {
    /**
     * No VPS config
     */
    400: unknown;
};

export type SimulationDirectPrepareResponses = {
    /**
     * Created
     */
    201: {
        intentId: string;
        linkId: string;
        sessionTag: string;
        paywallUrl: string;
        paywallPayload: string;
        paywallSignature: string;
        amount: number;
    };
};

export type SimulationDirectPrepareResponse = SimulationDirectPrepareResponses[keyof SimulationDirectPrepareResponses];

export type SimulationDirectStatusData = {
    body?: never;
    path: {
        intentId: string;
    };
    query?: never;
    url: '/admin/simulation/direct/status/{intentId}';
};

export type SimulationDirectStatusErrors = {
    /**
     * Intent not found
     */
    404: unknown;
};

export type SimulationDirectStatusResponses = {
    /**
     * OK
     */
    200: {
        intentId: string;
        status: string;
        providerRef: string | null;
        terminal: boolean;
        rawVpsStatus?: string | null;
        paymentServiceUrl?: string | null;
        settleError?: string;
        vpsRawResponse?: {
            [key: string]: unknown;
        };
        queryError?: string;
    };
};

export type SimulationDirectStatusResponse = SimulationDirectStatusResponses[keyof SimulationDirectStatusResponses];

export type SimulationDirectCleanupData = {
    body?: never;
    path: {
        intentId: string;
    };
    query?: never;
    url: '/admin/simulation/direct/cleanup/{intentId}';
};

export type SimulationDirectCleanupResponses = {
    /**
     * OK
     */
    200: {
        deleted: {
            intents: number;
            links: number;
        };
    };
};

export type SimulationDirectCleanupResponse = SimulationDirectCleanupResponses[keyof SimulationDirectCleanupResponses];

export type SimulationPreauthPrepareData = {
    body?: {
        tenantId: string;
        amount?: number;
    };
    path?: never;
    query?: never;
    url: '/admin/simulation/preauth/prepare';
};

export type SimulationPreauthPrepareErrors = {
    /**
     * No VPS config
     */
    400: unknown;
};

export type SimulationPreauthPrepareResponses = {
    /**
     * Created
     */
    201: {
        intentId: string;
        linkId: string;
        sessionTag: string;
        paywallUrl: string;
        paywallPayload: string;
        paywallSignature: string;
        amount: number;
    };
};

export type SimulationPreauthPrepareResponse = SimulationPreauthPrepareResponses[keyof SimulationPreauthPrepareResponses];

export type SimulationPreauthStatusData = {
    body?: never;
    path: {
        intentId: string;
    };
    query?: never;
    url: '/admin/simulation/preauth/status/{intentId}';
};

export type SimulationPreauthStatusErrors = {
    /**
     * Intent not found
     */
    404: unknown;
};

export type SimulationPreauthStatusResponses = {
    /**
     * OK
     */
    200: {
        intentId: string;
        status: string;
        providerRef: string | null;
        terminal: boolean;
        authorized: boolean;
        rawVpsStatus?: string | null;
        paymentServiceUrl?: string | null;
        queryError?: string;
    };
};

export type SimulationPreauthStatusResponse = SimulationPreauthStatusResponses[keyof SimulationPreauthStatusResponses];

export type SimulationPreauthCaptureData = {
    body?: never;
    path: {
        intentId: string;
    };
    query?: never;
    url: '/admin/simulation/preauth/capture/{intentId}';
};

export type SimulationPreauthCaptureErrors = {
    /**
     * Wrong state / no provider ref
     */
    400: unknown;
    /**
     * Intent not found
     */
    404: unknown;
};

export type SimulationPreauthCaptureResponses = {
    /**
     * OK
     */
    200: IntentActionResult;
};

export type SimulationPreauthCaptureResponse = SimulationPreauthCaptureResponses[keyof SimulationPreauthCaptureResponses];

export type SimulationPreauthCancelData = {
    body?: never;
    path: {
        intentId: string;
    };
    query?: never;
    url: '/admin/simulation/preauth/cancel/{intentId}';
};

export type SimulationPreauthCancelErrors = {
    /**
     * Wrong state / no provider ref
     */
    400: unknown;
    /**
     * Intent not found
     */
    404: unknown;
};

export type SimulationPreauthCancelResponses = {
    /**
     * OK
     */
    200: IntentActionResult;
};

export type SimulationPreauthCancelResponse = SimulationPreauthCancelResponses[keyof SimulationPreauthCancelResponses];

export type SimulationPreauthCleanupData = {
    body?: never;
    path: {
        intentId: string;
    };
    query?: never;
    url: '/admin/simulation/preauth/cleanup/{intentId}';
};

export type SimulationPreauthCleanupResponses = {
    /**
     * OK
     */
    200: {
        deleted: {
            intents: number;
            links: number;
        };
    };
};

export type SimulationPreauthCleanupResponse = SimulationPreauthCleanupResponses[keyof SimulationPreauthCleanupResponses];

export type GetLedgerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ledger';
};

export type GetLedgerResponses = {
    /**
     * OK
     */
    200: LedgerResponse;
};

export type GetLedgerResponse = GetLedgerResponses[keyof GetLedgerResponses];

export type ListFeeSchedulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fee-schedules';
};

export type ListFeeSchedulesResponses = {
    /**
     * OK
     */
    200: Array<FeeSchedule>;
};

export type ListFeeSchedulesResponse = ListFeeSchedulesResponses[keyof ListFeeSchedulesResponses];

export type CreateFeeScheduleData = {
    body?: {
        name?: string | null;
        feeType: 'FLAT' | 'PERCENTAGE' | 'PER_METHOD' | 'TIERED';
        flatCents?: number | null;
        percentageBps?: number | null;
        perMethodCents?: {
            [key: string]: number;
        } | null;
        tiersCents?: Array<{
            upToCents: number;
            percentageBps: number;
        }> | null;
        currency?: string | null;
    };
    path?: never;
    query?: never;
    url: '/fee-schedules';
};

export type CreateFeeScheduleResponses = {
    /**
     * Created
     */
    201: FeeSchedule;
};

export type CreateFeeScheduleResponse = CreateFeeScheduleResponses[keyof CreateFeeScheduleResponses];

export type GetActiveFeeScheduleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fee-schedules/active';
};

export type GetActiveFeeScheduleErrors = {
    /**
     * No active fee schedule
     */
    404: unknown;
};

export type GetActiveFeeScheduleResponses = {
    /**
     * OK
     */
    200: FeeSchedule;
};

export type GetActiveFeeScheduleResponse = GetActiveFeeScheduleResponses[keyof GetActiveFeeScheduleResponses];

export type ListSettlementPoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settlement-policies';
};

export type ListSettlementPoliciesResponses = {
    /**
     * OK
     */
    200: Array<SettlementPolicy>;
};

export type ListSettlementPoliciesResponse = ListSettlementPoliciesResponses[keyof ListSettlementPoliciesResponses];

export type CreateSettlementPolicyData = {
    body?: {
        name?: string | null;
        industry?: string | null;
        mcc?: string | null;
        availabilityMode?: 'IMMEDIATE' | 'DELAY' | 'ON_FULFILLMENT' | 'ON_COLLECTION';
        availabilityDelayDays?: number | null;
        reserveType?: 'NONE' | 'FIXED' | 'ROLLING';
        reservePercentageBps?: number | null;
        reserveHoldDays?: number | null;
        reserveFixedCents?: number | null;
        payoutSchedule?: 'MANUAL' | 'AUTO_DAILY' | 'AUTO_WEEKLY' | 'AUTO_MONTHLY' | 'THRESHOLD' | 'INSTANT';
        payoutMinCents?: number | null;
        reversalFunding?: 'NET_FROM_AVAILABLE' | 'DEBIT_RESERVE' | 'INVOICE_TENANT' | 'ALLOW_NEGATIVE';
        allowNegative?: boolean | null;
        splittingEnabled?: boolean | null;
        payoutRail?: 'STRIPE_CONNECT' | 'MANUAL';
        feeScheduleId?: string | null;
    };
    path?: never;
    query?: never;
    url: '/settlement-policies';
};

export type CreateSettlementPolicyResponses = {
    /**
     * Created
     */
    201: SettlementPolicy;
};

export type CreateSettlementPolicyResponse = CreateSettlementPolicyResponses[keyof CreateSettlementPolicyResponses];

export type GetActiveSettlementPolicyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settlement-policies/active';
};

export type GetActiveSettlementPolicyErrors = {
    /**
     * No active settlement policy
     */
    404: unknown;
};

export type GetActiveSettlementPolicyResponses = {
    /**
     * OK
     */
    200: SettlementPolicy;
};

export type GetActiveSettlementPolicyResponse = GetActiveSettlementPolicyResponses[keyof GetActiveSettlementPolicyResponses];

export type GetSettlementSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settlement/summary';
};

export type GetSettlementSummaryResponses = {
    /**
     * OK
     */
    200: SettlementSummary;
};

export type GetSettlementSummaryResponse = GetSettlementSummaryResponses[keyof GetSettlementSummaryResponses];

export type GetFinanceConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/finance-config';
};

export type GetFinanceConfigResponses = {
    /**
     * OK
     */
    200: FinanceConfigResponse;
};

export type GetFinanceConfigResponse = GetFinanceConfigResponses[keyof GetFinanceConfigResponses];

export type UpdateFinanceConfigData = {
    body?: {
        capabilities: Array<'INSTANT_CAPTURE' | 'PREAUTH_CAPTURE' | 'WALLET' | 'SUBSCRIPTIONS' | 'INSTALLMENTS' | 'MARKETPLACE_SPLITS'>;
        preset?: string | null;
        walletCommissionBasis?: 'usage' | 'load';
    };
    path?: never;
    query?: never;
    url: '/finance-config';
};

export type UpdateFinanceConfigResponses = {
    /**
     * OK
     */
    200: FinanceConfigResponse;
};

export type UpdateFinanceConfigResponse = UpdateFinanceConfigResponses[keyof UpdateFinanceConfigResponses];

export type ListPayoutsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/payouts';
};

export type ListPayoutsResponses = {
    /**
     * OK
     */
    200: Array<Payout>;
};

export type ListPayoutsResponse = ListPayoutsResponses[keyof ListPayoutsResponses];

export type CreatePayoutData = {
    body?: {
        idempotencyKey: string;
        provider: 'NAPS' | 'VPS' | 'STRIPE' | 'PAYPAL' | 'ADYEN';
        method?: 'BANK_TRANSFER' | 'CARD' | 'WALLET';
    };
    path?: never;
    query?: never;
    url: '/payouts';
};

export type CreatePayoutResponses = {
    /**
     * Created
     */
    201: Payout;
};

export type CreatePayoutResponse = CreatePayoutResponses[keyof CreatePayoutResponses];

export type GetPayoutData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payouts/{id}';
};

export type GetPayoutErrors = {
    /**
     * Payout not found
     */
    404: unknown;
};

export type GetPayoutResponses = {
    /**
     * OK
     */
    200: Payout;
};

export type GetPayoutResponse = GetPayoutResponses[keyof GetPayoutResponses];

export type CancelPayoutData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payouts/{id}/cancel';
};

export type CancelPayoutResponses = {
    /**
     * OK
     */
    200: Payout;
};

export type CancelPayoutResponse = CancelPayoutResponses[keyof CancelPayoutResponses];

export type ProcessPayoutData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payouts/{id}/process';
};

export type ProcessPayoutErrors = {
    /**
     * Payout not found
     */
    404: unknown;
};

export type ProcessPayoutResponses = {
    /**
     * OK
     */
    200: Payout;
};

export type ProcessPayoutResponse = ProcessPayoutResponses[keyof ProcessPayoutResponses];

export type ListDisputesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/disputes';
};

export type ListDisputesResponses = {
    /**
     * OK
     */
    200: Array<Dispute>;
};

export type ListDisputesResponse = ListDisputesResponses[keyof ListDisputesResponses];

export type CreateDisputeData = {
    body?: {
        providerDisputeId: string;
        provider: 'NAPS' | 'VPS' | 'STRIPE' | 'PAYPAL' | 'ADYEN';
        amount: number;
        feeAmount?: number | null;
        currency?: string | null;
        reason?: string | null;
        paymentIntentId?: string | null;
        evidenceDueDate?: string | null;
    };
    path?: never;
    query?: never;
    url: '/disputes';
};

export type CreateDisputeResponses = {
    /**
     * Created
     */
    201: Dispute;
};

export type CreateDisputeResponse = CreateDisputeResponses[keyof CreateDisputeResponses];

export type GetDisputeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/disputes/{id}';
};

export type GetDisputeErrors = {
    /**
     * Dispute not found
     */
    404: unknown;
};

export type GetDisputeResponses = {
    /**
     * OK
     */
    200: Dispute;
};

export type GetDisputeResponse = GetDisputeResponses[keyof GetDisputeResponses];

export type ResolveDisputeData = {
    body?: {
        outcome: 'WON' | 'LOST';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/disputes/{id}/resolve';
};

export type ResolveDisputeErrors = {
    /**
     * Dispute not found
     */
    404: unknown;
};

export type ResolveDisputeResponses = {
    /**
     * OK
     */
    200: Dispute;
};

export type ResolveDisputeResponse = ResolveDisputeResponses[keyof ResolveDisputeResponses];

export type ListSplitPartiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/split-parties';
};

export type ListSplitPartiesResponses = {
    /**
     * OK
     */
    200: Array<SplitParty>;
};

export type ListSplitPartiesResponse = ListSplitPartiesResponses[keyof ListSplitPartiesResponses];

export type CreateSplitPartyData = {
    body?: {
        slug: string;
        name: string;
        type?: 'PLATFORM' | 'SUB_MERCHANT' | 'VENDOR' | 'AFFILIATE' | 'ESCROW';
    };
    path?: never;
    query?: never;
    url: '/split-parties';
};

export type CreateSplitPartyResponses = {
    /**
     * Created
     */
    201: SplitParty;
};

export type CreateSplitPartyResponse = CreateSplitPartyResponses[keyof CreateSplitPartyResponses];

export type GetSplitPartyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/split-parties/{id}';
};

export type GetSplitPartyErrors = {
    /**
     * Split party not found
     */
    404: unknown;
};

export type GetSplitPartyResponses = {
    /**
     * OK
     */
    200: SplitParty;
};

export type GetSplitPartyResponse = GetSplitPartyResponses[keyof GetSplitPartyResponses];

export type DeactivateSplitPartyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/split-parties/{id}/deactivate';
};

export type DeactivateSplitPartyResponses = {
    /**
     * OK
     */
    200: SplitParty;
};

export type DeactivateSplitPartyResponse = DeactivateSplitPartyResponses[keyof DeactivateSplitPartyResponses];

export type ListSplitRulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/split-rules';
};

export type ListSplitRulesResponses = {
    /**
     * OK
     */
    200: Array<SplitRule>;
};

export type ListSplitRulesResponse = ListSplitRulesResponses[keyof ListSplitRulesResponses];

export type CreateSplitRuleData = {
    body?: {
        name: string;
        trigger?: 'AT_CAPTURE' | 'ON_USAGE' | 'MANUAL';
        shares: Array<{
            partyId: string;
            shareBps: number;
        }>;
    };
    path?: never;
    query?: never;
    url: '/split-rules';
};

export type CreateSplitRuleResponses = {
    /**
     * Created
     */
    201: SplitRule;
};

export type CreateSplitRuleResponse = CreateSplitRuleResponses[keyof CreateSplitRuleResponses];

export type GetSplitRuleData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/split-rules/{id}';
};

export type GetSplitRuleErrors = {
    /**
     * Split rule not found
     */
    404: unknown;
};

export type GetSplitRuleResponses = {
    /**
     * OK
     */
    200: SplitRule;
};

export type GetSplitRuleResponse = GetSplitRuleResponses[keyof GetSplitRuleResponses];

export type DeactivateSplitRuleData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/split-rules/{id}/deactivate';
};

export type DeactivateSplitRuleResponses = {
    /**
     * OK
     */
    200: SplitRule;
};

export type DeactivateSplitRuleResponse = DeactivateSplitRuleResponses[keyof DeactivateSplitRuleResponses];

export type ListSplitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/splits';
};

export type ListSplitsResponses = {
    /**
     * OK
     */
    200: Array<Split>;
};

export type ListSplitsResponse = ListSplitsResponses[keyof ListSplitsResponses];

export type ExecuteSplitData = {
    body?: {
        sourceType: string;
        sourceId: string;
        sourceCents: number;
        splitRuleId?: string | null;
        trigger?: 'AT_CAPTURE' | 'ON_USAGE' | 'MANUAL';
        shares?: Array<{
            partyId: string;
            shareBps: number;
        }> | null;
        held?: boolean | null;
        heldUntil?: string | null;
    };
    path?: never;
    query?: never;
    url: '/splits';
};

export type ExecuteSplitResponses = {
    /**
     * Created
     */
    201: Array<Split>;
};

export type ExecuteSplitResponse = ExecuteSplitResponses[keyof ExecuteSplitResponses];

export type GetSplitData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/splits/{id}';
};

export type GetSplitErrors = {
    /**
     * Split not found
     */
    404: unknown;
};

export type GetSplitResponses = {
    /**
     * OK
     */
    200: Split;
};

export type GetSplitResponse = GetSplitResponses[keyof GetSplitResponses];

export type ReleaseSplitData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/splits/{id}/release';
};

export type ReleaseSplitErrors = {
    /**
     * Split not found
     */
    404: unknown;
};

export type ReleaseSplitResponses = {
    /**
     * OK
     */
    200: Split;
};

export type ReleaseSplitResponse = ReleaseSplitResponses[keyof ReleaseSplitResponses];

export type ListReconciliationReportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reconciliation-reports';
};

export type ListReconciliationReportsResponses = {
    /**
     * OK
     */
    200: Array<ReconciliationReport>;
};

export type ListReconciliationReportsResponse = ListReconciliationReportsResponses[keyof ListReconciliationReportsResponses];

export type CreateReconciliationReportData = {
    body?: {
        provider: 'NAPS' | 'VPS' | 'STRIPE' | 'PAYPAL' | 'ADYEN';
        currency?: string | null;
        periodStart?: string | null;
        periodEnd?: string | null;
        lines: Array<{
            reference: string;
            amountCents: number;
        }>;
    };
    path?: never;
    query?: never;
    url: '/reconciliation-reports';
};

export type CreateReconciliationReportResponses = {
    /**
     * Created
     */
    201: ReconciliationReport;
};

export type CreateReconciliationReportResponse = CreateReconciliationReportResponses[keyof CreateReconciliationReportResponses];

export type GetReconciliationReportData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/reconciliation-reports/{id}';
};

export type GetReconciliationReportErrors = {
    /**
     * Reconciliation report not found
     */
    404: unknown;
};

export type GetReconciliationReportResponses = {
    /**
     * OK
     */
    200: ReconciliationReport;
};

export type GetReconciliationReportResponse = GetReconciliationReportResponses[keyof GetReconciliationReportResponses];

export type RunReconciliationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/reconciliation-reports/{id}/run';
};

export type RunReconciliationErrors = {
    /**
     * Reconciliation report not found
     */
    404: unknown;
};

export type RunReconciliationResponses = {
    /**
     * OK
     */
    200: ReconciliationReport;
};

export type RunReconciliationResponse = RunReconciliationResponses[keyof RunReconciliationResponses];

export type ResolveReconciliationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/reconciliation-reports/{id}/resolve';
};

export type ResolveReconciliationErrors = {
    /**
     * Reconciliation report not found
     */
    404: unknown;
};

export type ResolveReconciliationResponses = {
    /**
     * OK
     */
    200: ReconciliationReport;
};

export type ResolveReconciliationResponse = ResolveReconciliationResponses[keyof ResolveReconciliationResponses];

export type ListSettlementStatementsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settlement-statements';
};

export type ListSettlementStatementsResponses = {
    /**
     * OK
     */
    200: Array<SettlementStatement>;
};

export type ListSettlementStatementsResponse = ListSettlementStatementsResponses[keyof ListSettlementStatementsResponses];

export type CreateSettlementStatementData = {
    body?: {
        periodStart: string | null;
        periodEnd: string | null;
        currency?: string | null;
    };
    path?: never;
    query?: never;
    url: '/settlement-statements';
};

export type CreateSettlementStatementResponses = {
    /**
     * Created
     */
    201: SettlementStatement;
};

export type CreateSettlementStatementResponse = CreateSettlementStatementResponses[keyof CreateSettlementStatementResponses];

export type GetSettlementStatementData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/settlement-statements/{id}';
};

export type GetSettlementStatementErrors = {
    /**
     * Settlement statement not found
     */
    404: unknown;
};

export type GetSettlementStatementResponses = {
    /**
     * OK
     */
    200: SettlementStatement;
};

export type GetSettlementStatementResponse = GetSettlementStatementResponses[keyof GetSettlementStatementResponses];

export type FinalizeSettlementStatementData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/settlement-statements/{id}/finalize';
};

export type FinalizeSettlementStatementErrors = {
    /**
     * Settlement statement not found
     */
    404: unknown;
};

export type FinalizeSettlementStatementResponses = {
    /**
     * OK
     */
    200: SettlementStatement;
};

export type FinalizeSettlementStatementResponse = FinalizeSettlementStatementResponses[keyof FinalizeSettlementStatementResponses];

export type VoidSettlementStatementData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/settlement-statements/{id}/void';
};

export type VoidSettlementStatementErrors = {
    /**
     * Settlement statement not found
     */
    404: unknown;
};

export type VoidSettlementStatementResponses = {
    /**
     * OK
     */
    200: SettlementStatement;
};

export type VoidSettlementStatementResponse = VoidSettlementStatementResponses[keyof VoidSettlementStatementResponses];

export type GetOnboardingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/onboarding';
};

export type GetOnboardingErrors = {
    /**
     * Onboarding not found
     */
    404: unknown;
};

export type GetOnboardingResponses = {
    /**
     * OK
     */
    200: MerchantOnboarding;
};

export type GetOnboardingResponse = GetOnboardingResponses[keyof GetOnboardingResponses];

export type UpsertOnboardingData = {
    body?: {
        legalName?: string | null;
        entityType?: string | null;
        registrationNumber?: string | null;
        country?: string | null;
        businessAddress?: string | null;
        website?: string | null;
        contactEmail?: string | null;
        industry?: string | null;
        mcc?: string | null;
        riskTier?: 'LOW' | 'MEDIUM' | 'HIGH';
    };
    path?: never;
    query?: never;
    url: '/onboarding';
};

export type UpsertOnboardingResponses = {
    /**
     * OK
     */
    200: MerchantOnboarding;
};

export type UpsertOnboardingResponse = UpsertOnboardingResponses[keyof UpsertOnboardingResponses];

export type SubmitOnboardingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/onboarding/submit';
};

export type SubmitOnboardingErrors = {
    /**
     * Onboarding not found
     */
    404: unknown;
};

export type SubmitOnboardingResponses = {
    /**
     * OK
     */
    200: MerchantOnboarding;
};

export type SubmitOnboardingResponse = SubmitOnboardingResponses[keyof SubmitOnboardingResponses];

export type ApproveOnboardingData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/admin/onboarding/{tenantId}/approve';
};

export type ApproveOnboardingErrors = {
    /**
     * Onboarding not found
     */
    404: unknown;
};

export type ApproveOnboardingResponses = {
    /**
     * OK
     */
    200: MerchantOnboarding & {
        policySpec: OnboardingPolicySpec;
    };
};

export type ApproveOnboardingResponse = ApproveOnboardingResponses[keyof ApproveOnboardingResponses];

export type RejectOnboardingData = {
    body?: {
        reason: string;
    };
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/admin/onboarding/{tenantId}/reject';
};

export type RejectOnboardingErrors = {
    /**
     * Onboarding not found
     */
    404: unknown;
};

export type RejectOnboardingResponses = {
    /**
     * OK
     */
    200: MerchantOnboarding;
};

export type RejectOnboardingResponse = RejectOnboardingResponses[keyof RejectOnboardingResponses];

export type RequestInfoOnboardingData = {
    body?: {
        notes: string;
    };
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/admin/onboarding/{tenantId}/request-info';
};

export type RequestInfoOnboardingErrors = {
    /**
     * Onboarding not found
     */
    404: unknown;
};

export type RequestInfoOnboardingResponses = {
    /**
     * OK
     */
    200: MerchantOnboarding;
};

export type RequestInfoOnboardingResponse = RequestInfoOnboardingResponses[keyof RequestInfoOnboardingResponses];

export type AdminExecutePayoutData = {
    body?: {
        externalReference: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/payouts/{id}/execute';
};

export type AdminExecutePayoutErrors = {
    /**
     * Payout not found
     */
    404: unknown;
};

export type AdminExecutePayoutResponses = {
    /**
     * OK
     */
    200: {
        id: string;
        status: string;
        providerTransferId: string | null;
        externalReference: string;
    };
};

export type AdminExecutePayoutResponse = AdminExecutePayoutResponses[keyof AdminExecutePayoutResponses];

export type AdminListPayoutsData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
        page?: string;
        limit?: string;
    };
    url: '/admin/payouts';
};

export type AdminListPayoutsResponses = {
    /**
     * OK
     */
    200: {
        data: Array<Payout & {
            tenantId: string;
            tenantName: string;
            tenantSlug: string;
        }>;
        total: number;
        page: number;
        limit: number;
    };
};

export type AdminListPayoutsResponse = AdminListPayoutsResponses[keyof AdminListPayoutsResponses];

export type AdminListOnboardingData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
        page?: string;
        limit?: string;
    };
    url: '/admin/onboarding';
};

export type AdminListOnboardingResponses = {
    /**
     * OK
     */
    200: {
        data: Array<MerchantOnboarding & {
            tenantName: string;
            tenantSlug: string;
        }>;
        total: number;
        page: number;
        limit: number;
    };
};

export type AdminListOnboardingResponse = AdminListOnboardingResponses[keyof AdminListOnboardingResponses];

export type AdminListDisputesData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
        page?: string;
        limit?: string;
    };
    url: '/admin/disputes';
};

export type AdminListDisputesResponses = {
    /**
     * OK
     */
    200: {
        data: Array<Dispute & {
            tenantId: string;
            tenantName: string;
            tenantSlug: string;
        }>;
        total: number;
        page: number;
        limit: number;
    };
};

export type AdminListDisputesResponse = AdminListDisputesResponses[keyof AdminListDisputesResponses];

export type AdminListReconciliationReportsData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
        page?: string;
        limit?: string;
    };
    url: '/admin/reconciliation-reports';
};

export type AdminListReconciliationReportsResponses = {
    /**
     * OK
     */
    200: {
        data: Array<{
            id: string;
            tenantId: string;
            tenantName: string;
            tenantSlug: string;
            provider: string;
            currency: string;
            periodStart: string | null;
            periodEnd: string | null;
            status: string;
            summary: {
                [key: string]: unknown;
            } | null;
            lineCount: number;
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
        page: number;
        limit: number;
    };
};

export type AdminListReconciliationReportsResponse = AdminListReconciliationReportsResponses[keyof AdminListReconciliationReportsResponses];

export type AdminListSettlementStatementsData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
        page?: string;
        limit?: string;
    };
    url: '/admin/settlement-statements';
};

export type AdminListSettlementStatementsResponses = {
    /**
     * OK
     */
    200: {
        data: Array<{
            id: string;
            tenantId: string;
            tenantName: string;
            tenantSlug: string;
            periodStart: string;
            periodEnd: string;
            currency: string;
            status: string;
            openingBalanceCents: number;
            closingBalanceCents: number;
            netCents: number;
            finalizedAt: string | null;
            itemCount: number;
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
        page: number;
        limit: number;
    };
};

export type AdminListSettlementStatementsResponse = AdminListSettlementStatementsResponses[keyof AdminListSettlementStatementsResponses];

export type AdminListRiskDecisionsData = {
    body?: never;
    path?: never;
    query?: {
        verdict?: string;
        page?: string;
        limit?: string;
    };
    url: '/admin/risk-decisions';
};

export type AdminListRiskDecisionsResponses = {
    /**
     * OK
     */
    200: {
        data: Array<{
            id: string;
            tenantId: string;
            tenantName: string;
            tenantSlug: string;
            verdict: string | null;
            provider: string;
            correlationId: string;
            paymentLinkId: string | null;
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
        page: number;
        limit: number;
    };
};

export type AdminListRiskDecisionsResponse = AdminListRiskDecisionsResponses[keyof AdminListRiskDecisionsResponses];

export type AdminResolveRiskDecisionData = {
    body?: {
        verdict: 'ALLOW' | 'BLOCK';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/risk-decisions/{id}/resolve';
};

export type AdminResolveRiskDecisionResponses = {
    /**
     * OK
     */
    200: {
        id: string;
        verdict: string | null;
        status: string;
        updatedAt: string;
    };
};

export type AdminResolveRiskDecisionResponse = AdminResolveRiskDecisionResponses[keyof AdminResolveRiskDecisionResponses];

export type AdminResolveDisputeData = {
    body?: {
        outcome: 'WON' | 'LOST';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/disputes/{id}/resolve';
};

export type AdminResolveDisputeResponses = {
    /**
     * OK
     */
    200: {
        id: string;
        status: string;
        updatedAt: string;
    };
};

export type AdminResolveDisputeResponse = AdminResolveDisputeResponses[keyof AdminResolveDisputeResponses];

export type AdminResolveReconciliationReportData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/reconciliation-reports/{id}/resolve';
};

export type AdminResolveReconciliationReportResponses = {
    /**
     * OK
     */
    200: {
        id: string;
        status: string;
        updatedAt: string;
    };
};

export type AdminResolveReconciliationReportResponse = AdminResolveReconciliationReportResponses[keyof AdminResolveReconciliationReportResponses];

export type AdminFinalizeSettlementStatementData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/settlement-statements/{id}/finalize';
};

export type AdminFinalizeSettlementStatementResponses = {
    /**
     * OK
     */
    200: {
        id: string;
        status: string;
        updatedAt: string;
    };
};

export type AdminFinalizeSettlementStatementResponse = AdminFinalizeSettlementStatementResponses[keyof AdminFinalizeSettlementStatementResponses];

export type AdminVoidSettlementStatementData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/settlement-statements/{id}/void';
};

export type AdminVoidSettlementStatementResponses = {
    /**
     * OK
     */
    200: {
        id: string;
        status: string;
        updatedAt: string;
    };
};

export type AdminVoidSettlementStatementResponse = AdminVoidSettlementStatementResponses[keyof AdminVoidSettlementStatementResponses];

export type ListWalletsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/wallets';
};

export type ListWalletsResponses = {
    /**
     * OK
     */
    200: Array<Wallet>;
};

export type ListWalletsResponse = ListWalletsResponses[keyof ListWalletsResponses];

export type CreateWalletData = {
    body?: {
        ownerType: 'TENANT' | 'CUSTOMER';
        ownerId: string;
        currency?: string | null;
    };
    path?: never;
    query?: never;
    url: '/wallets';
};

export type CreateWalletResponses = {
    /**
     * Created
     */
    201: Wallet;
};

export type CreateWalletResponse = CreateWalletResponses[keyof CreateWalletResponses];

export type GetWalletData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/wallets/{id}';
};

export type GetWalletErrors = {
    /**
     * Wallet not found
     */
    404: unknown;
};

export type GetWalletResponses = {
    /**
     * OK
     */
    200: WalletDetail;
};

export type GetWalletResponse = GetWalletResponses[keyof GetWalletResponses];

export type TopUpWalletData = {
    body?: {
        amountCents: number;
        paymentIntentId?: string | null;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/wallets/{id}/topup';
};

export type TopUpWalletResponses = {
    /**
     * OK
     */
    200: WalletOpResponse;
};

export type TopUpWalletResponse = TopUpWalletResponses[keyof TopUpWalletResponses];

export type DebitWalletData = {
    body?: {
        amountCents: number;
        method?: string | null;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/wallets/{id}/debit';
};

export type DebitWalletResponses = {
    /**
     * OK
     */
    200: WalletOpResponse;
};

export type DebitWalletResponse = DebitWalletResponses[keyof DebitWalletResponses];

export type RefundWalletData = {
    body?: {
        amountCents: number;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/wallets/{id}/refund';
};

export type RefundWalletResponses = {
    /**
     * OK
     */
    200: WalletOpResponse;
};

export type RefundWalletResponse = RefundWalletResponses[keyof RefundWalletResponses];

export type AdjustWalletData = {
    body?: {
        amountCents: number;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/wallets/{id}/adjust';
};

export type AdjustWalletResponses = {
    /**
     * OK
     */
    200: WalletOpResponse;
};

export type AdjustWalletResponse = AdjustWalletResponses[keyof AdjustWalletResponses];
